#### Makefile : Build the local GTFoldPython module source
#### Author: Maxie D. Schmidt (maxieds@gmail.com)
#### Created: 2020.01.22

default:
	@cd ../ && make

clean:
	@cd ../ && make clean

test: 
	@cd ../ && make test

install: 
	@cd ../ && make install

